### ISSUE TITLE
你好，这个固件中的ssr可以用v2ray节点吗

### ISSUE THREAD

**Issue by GGGGiiss** [SaltedLeopold/padavan-RT-AC1200#1]
你好，这个固件中的ssr可以用v2ray节点吗？

**Comment by SaltedLeopold** [comment]
目前不能，这两天有时间我看看能不能整合个v2ray进去吧

**Comment by GGGGiiss** [comment]
好的，明白了，谢谢回复，如果添加了v2ray功能，可以的话，通知一下，十分感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LeopoldChan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月10日(星期一) 中午1:58
收件人:&nbsp;"SaltedLeopold/padavan-RT-AC1200"<padavan-RT-AC1200@noreply.github.com&gt;;
抄送:&nbsp;"iiss"<978837742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SaltedLeopold/padavan-RT-AC1200] 你好，这个固件中的ssr可以用v2ray节点吗 (#1)




目前不能，这两天有时间我看看能不能整合个v2ray进去吧
